name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main  # Change if your default branch is different

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
jobs:
  run-template:
    if: ${{ false }}             # <-- skip the template job entirely
    uses: ./.github/workflows/template.yml
    with:
      # inputs...
    secrets: inherit

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          channelId: live
          projectId: your-firebase-project-id

# .github/workflows/ci.yml  (example path)
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # ... previous steps

      - name: <THE FAILING STEP NAME>
        continue-on-error: true    # <-- add this line
        run: |
          # original command(s) here
- name: Setup Node
  uses: actions/setup-node@v4
  with:
    node-version: 18

- name: Install
  run: npm ci

- name: Run linters & autofix
  run: |
    # adjust commands to your project
    npm run lint -- --fix || true
    npm run format || true

- name: Commit & push changes if any
  run: |
    git config user.name "github-actions[bot]"
    git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
    git add -A
    if ! git diff --staged --quiet; then
      git commit -m "chore: apply autofixes [skip ci]" || true
      git push
    else
      echo "No changes to commit"
    fi